name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Init tools
        uses: ./.github/actions/init-tools

      - name: Build package
        run: uv build

  integration:
    permissions:
      contents: read
    uses: oarepo/oarepo/.github/workflows/repository-generation-test.yaml@main
    with:
      model_template: ${{ github.event.pull_request.head.repo.html_url }}
      model_template_version: ${{ github.event.pull_request.head.sha }}
      oarepo_app_ref: ${{ github.event.pull_request.head.sha }}
